codecov:
  strict_yaml_branch: master
coverage:
  status:
    project:
      default:
        threshold: 0
        if_no_uploads: failure
        if_ci_failed: failure
    patch: false
    changes: false
comment:
  layout: "header, diff, changes"
